import type { AureleanState } from "@/types/aurelean";

export const initialState: AureleanState = {
  suppliers: [
    {
      id: "cerruti",
      name: "Lanificio Cerruti",
      country: "Italy",
      countryCode: "IT",
      city: "Biella",
      category: "wool",
      material: "Super 150s worsted wool",
      moq: "30m",
      leadTimeWeeks: 6,
      tier: "A+",
      verified: true,
      reliability: 94,
      capabilityTier: "A+",
      stage: "approved",
      saved: false,
      certifications: ["AURELEAN Verified", "GOTS", "RWS Wool", "ISO 9001"],
      overview:
        "A historic Piedmont worsted mill specialising in Super 150s-180s wool, high-twist tropicals, and refined flannels. Vertically integrated from dyeing to finishing, with atelier-scale and production capacity.",
      featuredScore: 9
    },
    {
      id: "barberis",
      name: "Vitale Barberis",
      country: "Italy",
      countryCode: "IT",
      city: "Pray",
      category: "wool",
      material: "High-twist tropical wool",
      moq: "50m",
      leadTimeWeeks: 5,
      tier: "A",
      verified: true,
      reliability: 91,
      capabilityTier: "A",
      stage: "sampling",
      saved: false,
      certifications: ["AURELEAN Verified", "RWS Wool"],
      overview:
        "A refined wool house with deep tailoring references, fast lab-dip cycles, and consistent tropical wool delivery.",
      featuredScore: 8
    },
    {
      id: "loro-filati",
      name: "Loro Filati",
      country: "Italy",
      countryCode: "IT",
      city: "Quarona",
      category: "cashmere",
      material: "Double-faced cashmere",
      moq: "20m",
      leadTimeWeeks: 8,
      tier: "A+",
      verified: true,
      reliability: 93,
      capabilityTier: "A+",
      stage: "shortlisted",
      saved: false,
      certifications: ["AURELEAN Verified", "Traceable Cashmere"],
      overview:
        "Premium cashmere sourcing and finishing partner for low-volume luxury capsule development.",
      featuredScore: 10
    },
    {
      id: "nishijin",
      name: "Nishijin Atelier",
      country: "Japan",
      countryCode: "JP",
      city: "Kyoto",
      category: "silk",
      material: "Jacquard mulberry silk",
      moq: "15m",
      leadTimeWeeks: 7,
      tier: "A",
      verified: true,
      reliability: 91,
      capabilityTier: "A",
      stage: "sampling",
      saved: false,
      certifications: ["AURELEAN Verified", "Mulberry Silk"],
      overview:
        "Kyoto jacquard and habotai specialist with loom-direct sampling and ornate pattern development.",
      featuredScore: 9
    },
    {
      id: "libeco",
      name: "Libeco Mills",
      country: "Belgium",
      countryCode: "BE",
      city: "Meulebeke",
      category: "linen",
      material: "Wet-spun Belgian linen",
      moq: "40m",
      leadTimeWeeks: 4,
      tier: "A-",
      verified: true,
      reliability: 86,
      capabilityTier: "A-",
      stage: "approved",
      saved: false,
      certifications: ["AURELEAN Verified", "Masters of Linen"],
      overview:
        "European linen specialist with strong provenance documentation and dependable shirting weights.",
      featuredScore: 7
    },
    {
      id: "albini",
      name: "Albini 1876",
      country: "Italy",
      countryCode: "IT",
      city: "Bergamo",
      category: "cotton",
      material: "Giza 87 poplin",
      moq: "60m",
      leadTimeWeeks: 5,
      tier: "A",
      verified: true,
      reliability: 89,
      capabilityTier: "A",
      stage: "approved",
      saved: false,
      certifications: ["AURELEAN Verified", "Egyptian Cotton"],
      overview:
        "Fine shirting cotton supplier with stable colour standards and established luxury programs.",
      featuredScore: 8
    },
    {
      id: "gobi",
      name: "Gobi Combing Co.",
      country: "Mongolia",
      countryCode: "MN",
      city: "Ulaanbaatar",
      category: "cashmere",
      material: "Grade-A raw cashmere",
      moq: "100kg",
      leadTimeWeeks: 9,
      tier: "A-",
      verified: true,
      reliability: 88,
      capabilityTier: "A-",
      stage: "dialogue",
      saved: false,
      certifications: ["AURELEAN Verified", "Herd Traceable"],
      overview:
        "Combing-season traceability partner with early warnings on seasonal lead-time movement.",
      featuredScore: 8
    },
    {
      id: "solbiati",
      name: "Solbiati",
      country: "Italy",
      countryCode: "IT",
      city: "Como",
      category: "linen",
      material: "Linen-silk hopsack",
      moq: "35m",
      leadTimeWeeks: 6,
      tier: "B+",
      verified: true,
      reliability: 84,
      capabilityTier: "B+",
      stage: "shortlisted",
      saved: false,
      certifications: ["AURELEAN Verified"],
      overview:
        "Textured linen blends for tailoring and soft furnishing programs.",
      featuredScore: 7
    },
    {
      id: "schoeller",
      name: "Schoeller Tech",
      country: "Switzerland",
      countryCode: "CH",
      city: "Sevelen",
      category: "technical",
      material: "Bonded performance shell",
      moq: "80m",
      leadTimeWeeks: 7,
      tier: "B+",
      verified: true,
      reliability: 82,
      capabilityTier: "B+",
      stage: "dialogue",
      saved: false,
      certifications: ["AURELEAN Verified", "Bluesign"],
      overview:
        "Technical-shell specialist for performance capsule sourcing and outerwear trials.",
      featuredScore: 6
    },
    {
      id: "drago",
      name: "Drago Biella",
      country: "Italy",
      countryCode: "IT",
      city: "Biella",
      category: "wool",
      material: "Brushed flannel",
      moq: "45m",
      leadTimeWeeks: 6,
      tier: "A-",
      verified: true,
      reliability: 88,
      capabilityTier: "A-",
      stage: "approved",
      saved: false,
      certifications: ["AURELEAN Verified", "RWS Wool"],
      overview:
        "Brushed flannels and classic tailoring cloth with reliable mid-volume capacity.",
      featuredScore: 7
    },
    {
      id: "taroni",
      name: "Taroni Como",
      country: "Italy",
      countryCode: "IT",
      city: "Como",
      category: "silk",
      material: "Duchesse satin silk",
      moq: "25m",
      leadTimeWeeks: 6,
      tier: "A",
      verified: true,
      reliability: 90,
      capabilityTier: "A",
      stage: "dialogue",
      saved: false,
      certifications: ["AURELEAN Verified", "Silk Mark"],
      overview:
        "Como silk house for satin, duchesse, and structured eveningwear materials.",
      featuredScore: 8
    },
    {
      id: "thomas-mason",
      name: "Thomas Mason",
      country: "UK",
      countryCode: "GB",
      city: "Lancashire",
      category: "cotton",
      material: "Two-fold Sea Island cotton",
      moq: "50m",
      leadTimeWeeks: 5,
      tier: "A-",
      verified: true,
      reliability: 87,
      capabilityTier: "A-",
      stage: "shortlisted",
      saved: false,
      certifications: ["AURELEAN Verified"],
      overview:
        "Fine cotton shirting reference with heritage patterns and precise finishing.",
      featuredScore: 7
    }
  ],
  rfqs: [
    {
      id: "RFQ-2041",
      supplierId: "cerruti",
      supplierName: "Lanificio Cerruti",
      material: "Super 150s worsted wool",
      quantity: "120 m",
      status: "responded",
      bidsReceived: 4,
      updatedAtLabel: "2h ago",
      project: "FW26 Tailoring",
      targetDelivery: "Q3 2026",
      thread: [
        {
          author: "Elise Moreau",
          initials: "EM",
          body: "Requesting Super 150s in four colourways for the FW26 tailoring line. Please confirm availability and lab-dip turnaround.",
          time: "3 days ago"
        },
        {
          author: "Lanificio Cerruti",
          initials: "L",
          body: "Confirmed. All four colourways are in stock. Lab dips in eight days, bulk lead six weeks. Quote attached at €42/m DDP.",
          time: "2 hours ago"
        }
      ]
    },
    {
      id: "RFQ-2038",
      supplierId: "nishijin",
      supplierName: "Nishijin Atelier",
      material: "Jacquard mulberry silk",
      quantity: "40 m",
      status: "sampling",
      bidsReceived: 2,
      updatedAtLabel: "5h ago",
      project: "Eveningwear capsule",
      targetDelivery: "Q2 2026",
      thread: []
    },
    {
      id: "RFQ-2035",
      supplierId: "gobi",
      supplierName: "Gobi Combing Co.",
      material: "Grade-A raw cashmere",
      quantity: "200 kg",
      status: "sent",
      bidsReceived: 1,
      updatedAtLabel: "Yesterday",
      project: "FW26 Knitwear",
      targetDelivery: "Q3 2026",
      thread: []
    },
    {
      id: "RFQ-2032",
      supplierId: "libeco",
      supplierName: "Libeco Mills",
      material: "Wet-spun Belgian linen",
      quantity: "300 m",
      status: "responded",
      bidsReceived: 5,
      updatedAtLabel: "2d ago",
      project: "SS26 Shirting",
      targetDelivery: "Q1 2026",
      thread: []
    },
    {
      id: "RFQ-2029",
      supplierId: "albini",
      supplierName: "Albini 1876",
      material: "Giza 87 poplin",
      quantity: "250 m",
      status: "draft",
      bidsReceived: 0,
      updatedAtLabel: "3d ago",
      project: "SS26 Shirting",
      targetDelivery: "Q1 2026",
      thread: []
    }
  ],
  bids: [
    {
      id: "BID-9001",
      rfqId: "RFQ-2041",
      supplierId: "cerruti",
      supplierName: "Lanificio Cerruti",
      countryCode: "IT",
      pricePerUnit: 42,
      currency: "EUR",
      leadTimeWeeks: 6,
      moq: "30 m",
      reliability: 94,
      bestValue: true,
      awarded: false
    },
    {
      id: "BID-9002",
      rfqId: "RFQ-2041",
      supplierId: "barberis",
      supplierName: "Vitale Barberis",
      countryCode: "IT",
      pricePerUnit: 46,
      currency: "EUR",
      leadTimeWeeks: 5,
      moq: "50 m",
      reliability: 91,
      bestValue: false,
      awarded: false
    },
    {
      id: "BID-9003",
      rfqId: "RFQ-2041",
      supplierId: "drago",
      supplierName: "Drago Biella",
      countryCode: "IT",
      pricePerUnit: 44,
      currency: "EUR",
      leadTimeWeeks: 6,
      moq: "45 m",
      reliability: 88,
      bestValue: false,
      awarded: false
    },
    {
      id: "BID-9004",
      rfqId: "RFQ-2041",
      supplierId: "thomas-mason",
      supplierName: "Fox Brothers",
      countryCode: "GB",
      pricePerUnit: 51,
      currency: "EUR",
      leadTimeWeeks: 7,
      moq: "40 m",
      reliability: 85,
      bestValue: false,
      awarded: false
    }
  ],
  memories: [
    {
      id: "MEM-1",
      kind: "Decision",
      title: "Awarded FW26 wool to Lanificio Cerruti",
      body:
        "Selected Cerruti over Barberis and Drago on best value (€42/m, 12% under budget) and highest reliability. Barberis retained as backup supplier.",
      entities: ["Cerruti", "RFQ-2041", "FW26 Tailoring"],
      time: "2h ago",
      group: "Today"
    },
    {
      id: "MEM-2",
      kind: "Sample",
      title: "Nishijin silk sample dispatched",
      body:
        "Jacquard mulberry silk lab dips shipped for the eveningwear capsule. Expected arrival in four days; approval gate set.",
      entities: ["Nishijin", "RFQ-2038", "Eveningwear"],
      time: "5h ago",
      group: "Today"
    },
    {
      id: "MEM-3",
      kind: "Signal",
      title: "Cashmere lead times trending +3 weeks",
      body:
        "AURELEAN detected seasonal lead-time inflation across Mongolian cashmere suppliers. Flagged for the FW26 knitwear plan with a recommendation to sample earlier.",
      entities: ["Cashmere", "Gobi Combing", "Market signal"],
      time: "2 days ago",
      group: "This week"
    },
    {
      id: "MEM-4",
      kind: "Decision",
      title: "Approved Libeco linen for SS26 shirting",
      body:
        "Wet-spun Belgian linen approved after lab-dip review. Locked at €68/m with a four-week lead. Provenance and certification verified.",
      entities: ["Libeco", "SS26 Shirting"],
      time: "3 days ago",
      group: "This week"
    },
    {
      id: "MEM-5",
      kind: "Spec",
      title: "Defined FW26 tailoring fabric brief",
      body:
        "Locked the spec for the FW26 tailoring line: Super 150s-180s worsted, 240-260 g/m, four core colourways. This brief now anchors all related RFQs.",
      entities: ["FW26 Tailoring", "Spec"],
      time: "2 weeks ago",
      group: "Earlier"
    }
  ],
  accessRequests: [],
  sampleRequests: []
};

